### PR TITLE
Fix python auto-generated imports

### PR DESCRIPTION
**Pull request by pablojorge**

### CODE REVIEW

**Review by mpfluger — APPROVED** [review]

**Review by Wrathcoin — APPROVED** [review]

**Review by arslan-raza-143 — COMMENTED** [review]
[]()

**Review by arslan-raza-143 — COMMENTED** [review]
- [ ]

**Review by arslan-raza-143 — COMMENTED** [review]
[]()

**Review by Lizzy127 — COMMENTED** [review]
Supporting

**Pull request merged**
